---
- name: Deploys VM
  hosts: localhost
  gather_facts: yes
  become: true
  vars:
    vms:
      - vm: guest-VM1
        vcpus: 2
        ram_mb: 2048
        net: Sw1  # Internt
        net2: Sw2 # L2
        ssh_pub_key: /home/vmadm/.ssh/id_rsa.pub
        disk_size: 12
      - vm: guest-VM2
        vcpus: 2
        ram_mb: 2048
        net: Sw1  # Internt
        net2: Sw3 # L3
        ssh_pub_key: /home/vmadm/.ssh/id_rsa.pub
        disk_size: 12

  tasks:
    - name: kvm_provision
      include_role:
        name: "./kvm_provision"
      vars:
        vm_name: "{{ item.vm }}"
        vm_vcpus: "{{ item.vcpus }}"
        vm_ram_mb: "{{ item.ram_mb }}"
        vm_net: "{{ item.net }}"
        ssh_key: "{{ item.ssh_pub_key }}"
        vm_net_2: "{{ item.net2 }}"
        vm_disk_size_G: "{{ item.disk_size }}"
      with_items: "{{ vms }}"
  