- name: Read a file and perform task for each line
  hosts: localhost
  tasks:
    - name: Read the file
      ansible.builtin.slurp:
        src: ./user_input.txt
      register: file_content
    
    - name: Initialize Output LOG
      ansible.builtin.shell: |
        echo "" > output_logs.txt
        

    - name: Process each line
      ansible.builtin.shell: |
        # Perform your task here with each line
        echo "Processing line: {{ item }}"
        echo "PYTHON LOG" >> output_logs.txt
        python3 ./create_custom_vm.py "{{ item }}" >> output_logs.txt
        echo "ANSIBLE LOG" >> output_logs.txt
        ansible-playbook create_vms.yml
      loop: "{{ file_content.content | b64decode | split('\n') }}"
      when: file_content.content is defined
      become: true